Repository sendgrid/rest, pull requests merged in 2018-10, with the labels that each got.

#74 Create README.md in use-cases
  use-cases/README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#82 Update contribution guides of the workflow
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#80 add first timers guide for newcomers
  FIRST-TIMERS.md
  static/img/github-fork.png
  static/img/github-sign-up.png
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#83 Follow godoc deprecation standards
  rest.go
Labels: difficulty: easy, hacktoberfest, status: code review request, status: hacktoberfest approved
