Repository sendgrid/rest, pull requests merged in 2020-01, with the labels that each got.

#62 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request, type: docs update

#96 chore: prep repo for automation
  .travis.yml
  CHANGELOG.md
  LICENSE.txt
  Makefile
Labels: status: code review request

#97 docs: baseline all the templated markdown docs
  .github/ISSUE_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  LICENSE.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  rest_test.go
Labels: status: code review request

#86 docs: Fixed link to bug report template
  CONTRIBUTING.md
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved
